execute_process(COMMAND "${GIT}" rev-parse --short HEAD RESULT_VARIABLE RET OUTPUT_VARIABLE DESCRIPTION OUTPUT_STRIP_TRAILING_WHITESPACE)

if(RET)
    message(WARNING "Cannot determine current revision. Make sure that you are building either from a Git working tree or from a source archive.")
    set(VERSION "${COMMIT}")
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/src/config/version.h.in" "${TO}")
else()
    string(STRIP "${DESCRIPTION}" COMMIT)
    set(VERSION "${COMMIT}")
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/src/config/version.h.in" "${TO}")
endif()
